    <!-- private $todos = [
        [
            "id" => 1,
            "project_id" => 1,
            "board_column" => "To Do",
            "order" => 1,
            "title" => "Buy groceries",
            "description" => "Purchase weekly groceries: milk, eggs, bread, fruits",
            "completed" => false,
            "due_date" => "2026-05-05",
            "priority" => "medium",
            "tags" => ["shopping", "home"],
            "status" => "open",
            "creator" => "Mona Ali",
            "assigned_to" => "Mona Ali",
            "labels" => ["errand"],
            "attachments" => [],
            "comments" => [],
            "color" => "#FF9800",
            "subtasks" => [
                ["id" => 101, "title" => "Check pantry", "completed" => true],
                ["id" => 102, "title" => "Make list", "completed" => false],
            ],
            "created_at" => "2026-04-01T09:00:00Z",
            "updated_at" => "2026-04-15T12:30:00Z",
        ],
        [
            "id" => 2,
            "project_id" => 2,
            "board_column" => "In Progress",
            "order" => 2,
            "title" => "Fix Authentication Bug",
            "description" => "Resolve the issue where users cannot reset their password via email link.",
            "completed" => false,
            "due_date" => "2026-05-10",
            "priority" => "high",
            "tags" => ["backend", "security"],
            "status" => "in_progress",
            "creator" => "Ahmed Salama",
            "assigned_to" => "Ahmed Salama",
            "labels" => ["bug", "critical"],
            "attachments" => ["error_log.txt"],
            "comments" => [["user" => "Dev Team", "text" => "Working on the SMTP settings now."]],
            "color" => "#F44336",
            "subtasks" => [
                ["id" => 201, "title" => "Check Mailer config", "completed" => true],
                ["id" => 202, "title" => "Verify token expiration", "completed" => false],
            ],
            "created_at" => "2026-05-01T10:00:00Z",
            "updated_at" => "2026-05-03T14:20:00Z",
        ],
        [
            "id" => 3,
            "project_id" => 1,
            "board_column" => "Completed",
            "order" => 3,
            "title" => "Design System UI Kit",
            "description" => "Create a consistent set of components for the main dashboard.",
            "completed" => true,
            "due_date" => "2026-04-20",
            "priority" => "low",
            "tags" => ["design", "frontend"],
            "status" => "closed",
            "creator" => "Sara Hassan",
            "assigned_to" => "Sara Hassan",
            "labels" => ["creative"],
            "attachments" => ["figma_link.url"],
            "comments" => [],
            "color" => "#4CAF50",
            "subtasks" => [
                ["id" => 301, "title" => "Define color palette", "completed" => true],
                ["id" => 302, "title" => "Design button states", "completed" => true],
            ],
            "created_at" => "2026-04-10T08:00:00Z",
            "updated_at" => "2026-04-20T17:00:00Z",
        ],
        [
            "id" => 4,
            "project_id" => 3,
            "board_column" => "To Do",
            "order" => 1,
            "title" => "Prepare Quarterly Report",
            "description" => "Gather sales data and financial metrics for the Q2 presentation.",
            "completed" => false,
            "due_date" => "2026-06-01",
            "priority" => "high",
            "tags" => ["business", "finance"],
            "status" => "open",
            "creator" => "Mona Ali",
            "assigned_to" => "John Doe",
            "labels" => ["report"],
            "attachments" => [],
            "comments" => [],
            "color" => "#2196F3",
            "subtasks" => [
                ["id" => 401, "title" => "Export CSV data", "completed" => false],
                ["id" => 402, "title" => "Create PowerPoint slides", "completed" => false],
            ],
            "created_at" => "2026-05-05T09:00:00Z",
            "updated_at" => "2026-05-05T09:00:00Z",
        ],
        [
            "id" => 5,
            "project_id" => 2,
            "board_column" => "Review",
            "order" => 4,
            "title" => "Update API Documentation",
            "description" => "Document the new endpoints for the mobile app team using Swagger.",
            "completed" => false,
            "due_date" => "2026-05-15",
            "priority" => "medium",
            "tags" => ["docs", "api"],
            "status" => "review",
            "creator" => "Ahmed Salama",
            "assigned_to" => "Mona Ali",
            "labels" => ["documentation"],
            "attachments" => [],
            "comments" => [["user" => "Mona Ali", "text" => "Waiting for final endpoint approval."]],
            "color" => "#9C27B0",
            "subtasks" => [
                ["id" => 501, "title" => "Write GET /users schema", "completed" => true],
                ["id" => 502, "title" => "Write POST /login schema", "completed" => true],
            ],
            "created_at" => "2026-05-01T11:00:00Z",
            "updated_at" => "2026-05-04T13:45:00Z",
        ],
    ]; -->
