use sakila;

-- 1. Create a function that takes actor_id and returns the concatenated first and last name of this actor.
delimiter /
create function actor_full_name(actor_id int)
returns varchar(100)
deterministic
begin
  return (
    select concat(first_name, ' ', last_name)
	from actor
    where actor.actor_id = actor_id
  );
end/
delimiter ;

select actor_full_name(1) as full_name;

-- 2. Create a function that takes customer_id and returns the total count of rentals made by this customer
delimiter /
create function rental_rotal_count(customer_id int)
returns int
deterministic
begin
  return (
    select count(*)
    from rental
    where rental.customer_id = customer_id
  );
end/
delimiter ;

select rental_rotal_count(1) as total_rentals;

-- 3. Create a function that takes a DECIMAL value and returns it as a formatted string with a dollar sign (e.g., $19.99).
delimiter /
create function dollar_formatted(amount decimal(10,2))
returns varchar(20)
deterministic
begin
  return concat('$', amount);
end/
delimiter ;

select dollar_formatted(34.56) as formatted_amount;


-- Stored Procedures
-- 4. Create a stored procedure that takes customer_id and returns a result set containing the full name, email, full address, and city of that customer.
delimiter /
create procedure get_customer_details(in customer_id int)
begin
  select 
    concat(c.first_name, ' ', c.last_name) as full_name,
    c.email,
    concat(a.address, ', ', ifnull(a.address2, ''), ', ', a.district) as full_address,
    ci.city
  from customer c
  join address a on c.address_id = a.address_id
  join city ci on a.city_id = ci.city_id
  where c.customer_id = customer_id;
end/
delimiter ;

call get_customer_details(2);


-- 5. Create a stored procedure that takes a start_date and end_date and returns the total revenue generated by each store during that period.
delimiter /
create procedure get_store_revenue(in start_date datetime, in end_date datetime)
begin
  select  s.store_id, sum(p.amount) as total_revenue
  from payment p
  join rental r on p.rental_id = r.rental_id
  join inventory i on r.inventory_id = i.inventory_id
  join store s on i.store_id = s.store_id
  where p.payment_date between start_date and end_date
  group by s.store_id;
end/
delimiter ;

call get_store_revenue('2000-01-01', '2026-01-01');


-- 6. Create a stored procedure that takes a partial string (e.g., 'dark') and returns all films whose titles contain that string, along with their ratings.
delimiter /
create procedure get_all_films(in film_name varchar(100))
begin
  select * 
  from film
  where title like concat('%', film_name, '%');
end/
delimiter ;

call get_all_films('dark');


-- 7. Create a stored procedure that takes customer_id and returns the name of the category (e.g., 'Action') that the customer rents most often
delimiter /
create procedure get_most_category(in customer_id int)
begin
  select  c.name as most_category, count(*) as rental_count
  from rental r
  join inventory i on r.inventory_id = i.inventory_id
  join film f on i.film_id = f.film_id
  join film_category fc on f.film_id = fc.film_id
  join category c on fc.category_id = c.category_id
  where r.customer_id = customer_id
  group by c.name
  order by rental_count desc
  limit 1;
end/
delimiter ;

call get_most_category(1);


-- Triggers
-- 8. Create a BEFORE UPDATE trigger on address table to set last_update = NOW() whenever a row is changed
delimiter /
create trigger before_address_update
before update on address
for each row
begin
  set new.last_update = NOW();
end/
delimiter ;

update address
set address = '123 zagazig St'
where address_id = 1;

select * from address where address_id = 1;

-- 9. Create a trigger to prevent an UPDATE to the staff table if the username is changed to 'admin'.
delimiter /
create trigger prevent_admin_username
before update on staff
for each row
begin
  if new.username = 'admin' then
    signal sqlstate '45000'
    set message_text = 'username cannot be changed';
  end if;
end/
delimiter ;

update staff
set username = 'admin'
where staff_id = 1;


-- 10. Create a BEFORE INSERT trigger on the customer table to ensure that any email address entered contains both an @ and a . symbol.
delimiter /
create trigger validate_customer_email
before insert on customer
for each row
begin
  if instr(new.email, '@') = 0 or instr(new.email, '.') = 0 then
    signal sqlstate '45000'
    set message_text = 'invalid email address';
  end if;
end/
delimiter ;

insert into customer (store_id, first_name, last_name, email, address_id, active, create_date)
values (1, 'abdo', 'ibrahim', 'invalidemail', 1, 1, NOW());


-- 11. Create a table film_price_history. Create an AFTER UPDATE trigger on the film table that records the old price, new price, and change date whenever the rental_rate is modified
create table film_price_history (
  history_id int auto_increment primary key,
  film_id int,
  old_price decimal(4,2),
  new_price decimal(4,2),
  change_date datetime
);

delimiter /
create trigger after_film_price_update
after update on film
for each row
begin
  if old.rental_rate != new.rental_rate then
    insert into film_price_history (film_id, old_price, new_price, change_date)
    values (new.film_id, old.rental_rate, new.rental_rate, now());
  end if;
end/
delimiter ;

update film
set rental_rate = 7.99
where film_id = 1;

select * from film where film_id = 1;
select * from film_price_history where film_id = 1;